### ISSUE TITLE
Update jsonld

### ISSUE THREAD

**Issue by tpluscode** [hypermedia-app/hydra-validator#14]
Here's the output of `npm ls jsonld`

```
hydra-validator@0.0.3
└─┬ rdf-fetch@1.0.0
  └─┬ rdf-formats-common@1.4.0
    ├─┬ rdf-parser-jsonld@1.1.0
    │ └── jsonld@0.4.12 
    └─┬ rdf-serializer-jsonld-ext@1.4.0
      └── jsonld@1.6.0 
```

The packages need to be updated to install latest jsonld parser

**Comment by tpluscode** [comment]
@bergos, what do I have to do here?

**Comment by bergos** [comment]
Better switch to [fetch-lite](https://github.com/rdfjs/fetch-lite) and [formats-common](https://github.com/rdfjs/formats-common). I'm working on a solution to migrate `rdf-fetch` to the rdfjs org, but this may take a little bit longer.
