### ISSUE TITLE
Required properties nested inside optional properties still required in strict mode

### ISSUE THREAD

**Issue by thewilkybarkid** [hypermedia-app/hydra-validator#58]
We run in strict mode, but it seems that properties are still required even if their optional parent isn't:

```
With Property hydra:member {
  Expect Type schema:Article
  Expect Property schema:name
}
```

fails if `hydra:member` is not present (`Strict mode requires that all steps are executed`), but they should only be tested if it is there. (`Skipping missing property http://www.w3.org/ns/hydra/core#member` happens correctly.)

(Refs https://httpapis.slack.com/archives/C1JP575EX/p1579613791005300).

**Comment by tpluscode** [comment]
Deployed as docker image `hydrofoil/hypertest:_0.4.1`
